# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 主题重新定义配置文件 V2
# 作者：EvanNotFound
# GitHub: https://github.com/EvanNotFound/hexo-theme-redefine
# 文档: https://redefine-docs.ohevan.com
# 演示: https://redefine.ohevan.com
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 基本信息 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/info
info:
  # 网站标题
  title: W1ndysの小屋
  # 网站副标题
  subtitle: 欲戴皇冠，必承其重
  # 作者姓名
  author: W1ndys
  # 网站 URL
  url: https://blog.w1ndys.top
# 基本信息 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 图片配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/defaults
defaults:
  # 网站图标
  favicon: /images/favicon.ico
  # 网站标志
  logo: /images/haixian.svg
  # 网站头像
  avatar: https://avatars.githubusercontent.com/u/109416673
# 图片配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 颜色 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/colors
colors:
  # 主色
  primary: "#A31F34"
  # 次色 (待定)
  secondary: "#1890ff"
  # 默认主题模式初始值 (将被 prefer-color-scheme 覆盖)
  default_mode: light # light, dark
# 颜色 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 网站自定义 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/global
global:
  # 自定义全局字体
  fonts:
    # 中文字体
    chinese:
      enable: false # 是否启用自定义中文字体
      family: # 字体家族
      url: # 字体 CSS 文件 URL
    # 英文字体
    english:
      enable: false # 是否启用自定义英文字体
      family: # 字体家族
      url: # 字体 CSS 文件 URL
    # 自定义标题字体 (导航栏，侧边栏)
    title:
      enable: false # 是否启用自定义标题字体
      family: # 字体家族
      url: # 字体 CSS 文件 URL
  # 内容最大宽度
  content_max_width: 1000px
  # 侧边栏宽度
  sidebar_width: 210px
  # 鼠标悬停效果
  hover:
    shadow: true # 阴影效果
    scale: true # 缩放效果
  # 滚动进度
  scroll_progress:
    bar: true # 进度条
    percentage: true # 百分比
  # 网站计数器
  website_counter:
    url: https://cn.vercount.one/js # 计数器 API URL (无需更改)
    enable: true # 是否启用网站计数器
    site_pv: true # 网站页面浏览量
    site_uv: true # 网站独立访客
    post_pv: true # 文章页面浏览量
  # 是否启用单页体验 (使用 swup)。参见 https://swup.js.org/。类似 pjax
  single_page: true
  # 是否启用首页全屏加载动画
  preloader:
    enable: true
    custom_message: 欢迎来到W1ndysの小屋 # 自定义消息。如果为空，将显示网站标题
  # 是否启用开放图谱
  open_graph:
    enable: true
    image: /images/redefine-og.webp # 默认 og:image
    description: W1ndysの小屋
  # Google Analytics
  google_analytics:
    enable: false # 是否启用 Google Analytics
    id: # Google Analytics 测量 ID
# 网站自定义 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# FontAwesome >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/basic/fontawesome
fontawesome: # Pro v6.2.1
  # 细体版本
  thin: false
  # 轻体版本
  light: false
  # 双音版本
  duotone: false
  # 锐利实心版本
  sharp_solid: false
# FontAwesome <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 首页横幅 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/home/home_banner
home_banner:
  # 是否启用首页横幅
  enable: true
  # 首页横幅样式
  style: fixed # static 或 fixed
  # 首页横幅图片
  image:
    light: https://pic1.zhimg.com/80/v2-b4e05912f591b51b9fa3e8aa4b9cba45.png # 亮模式
    dark: https://pic1.zhimg.com/80/v2-b4e05912f591b51b9fa3e8aa4b9cba45.png # 暗模式
  # 首页横幅标题
  title: W1ndysの小屋
  # 首页横幅副标题
  subtitle:
    text: ["一言加载中..."] # 副标题文本，数组
    hitokoto: # 一言配置
      enable: true # 是否启用一言
      show_author: true # 是否显示作者
      api: https://v1.hitokoto.cn # API URL，可添加类型，参见 https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0
    typing_speed: 100 # 打字速度 (毫秒)
    backing_speed: 80 # 退格速度 (毫秒)
    starting_delay: 500 # 开始延迟 (毫秒)
    backing_delay: 1500 # 退格延迟 (毫秒)
    loop: true # 是否循环
    smart_backspace: true # 是否智能退格
  # 首页横幅文本颜色
  text_color:
    light: "#fff" # 亮模式
    dark: "#d1d1b6" # 暗模式
  # 文本的具体样式
  text_style:
    # 标题字体大小
    title_size: 2.8rem
    # 副标题字体大小
    subtitle_size: 1.5rem
    # 标题和副标题之间的行高
    line_height: 1.2
  # 首页横幅自定义字体
  custom_font:
    # 是否启用自定义字体
    enable: false
    # 字体家族
    family:
    # 字体 CSS 文件 URL
    url:
  # 首页横幅社交链接
  social_links:
    # 是否启用
    enable: true
    # 社交链接样式
    style: default # default, reverse, center
    # 社交链接
    links:
      github: https://github.com/W1ndys # 你的 GitHub URL
      zhihu: https://www.zhihu.com/people/w1ndys # 你的知乎 URL
      email: w1ndys@outlook.com # 你的电子邮件
      # ...... # 你可以添加更多
    # 带有二维码抽屉的社交链接
    qrs:
      weixin: # 你的微信二维码图片 URL
      # ...... # 你可以添加更多
# 首页横幅 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 导航栏 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/home/navbar
navbar:
  # 自动隐藏导航栏
  auto_hide: true
  # 导航栏背景颜色
  color:
    left: "#f78736" # 左侧
    right: "#367df7" # 右侧
    transparency: 35 # 透明度 (10-99)
  # 导航栏宽度 (通常无需修改)
  width:
    home: 1200px # 首页
    pages: 1000px # 其他页面
  # 导航栏链接
  links:
    Archives:
      path: /archives
      icon: fa-regular fa-archive # 可以为空
    Categories:
      path: /categories
      icon: fa-regular fa-folder
    Tags:
      path: /tags
      icon: fa-regular fa-tags
    友链接力:
      icon: fa-train-subway
      submenus:
        异次元之旅: https://travel.moe/go.html?travel=on
        MIIT Travel: https://beian.miit.cn.com/go.php#/
        博客录: https://bokelu.suijiboke.gs
        笔墨迹: https://blogscn.fun/random.html
        博客圈: https://bokequan.cn/?suiji
        开往: https://www.travellings.cn/go.html

    # 相册:
    #   path: /masonry
    #   icon: fa-regular fa-image
    Friends:
      path: /links
      icon: fa-regular fa-link
    书签:
      icon: fa-solid fa-bookmark #图标
      path: /bookmarks/
    # About:
    #   icon: fa-regular fa-user
    #   submenus:
    #     Me: /about
    #     Github: https://github.com/EvanNotFound/hexo-theme-redefine
    #     Blog: https://ohevan.com
    #     Friends: /friends
    # Links:
    #   icon: fa-regular fa-link
    #   submenus:
    # Google: https://www.google.com
    # Baidu: https://www.baidu.com
    # Github: https://www.github.com
    # zhihu: https://www.zhihu.com
    # ...... # 你可以添加更多
  # 导航栏搜索 (本地搜索)。需要 hexo-generator-searchdb (npm i hexo-generator-searchdb)。参见 https://github.com/theme-next/hexo-generator-searchdb
  search:
    # 是否启用
    enable: true
    # 页面加载时预加载搜索数据
    preload: true
# 导航栏 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 首页文章设置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/home/home
home:
  # 侧边栏设置
  sidebar:
    enable: true # 是否启用侧边栏
    position: left # 侧边栏位置。left, right
    first_item: menu # 侧边栏的第一个项目。menu, info
    announcement: Welcome to W1ndys's Blog # 公告文本
    show_on_mobile: true # 是否在移动设备上显示侧边栏导航
    links:
      Archives:
        path: /archives
        icon: fa-regular fa-archive # 可以为空
      Tags:
        path: /tags
        icon: fa-regular fa-tags # 可以为空
      Categories:
        path: /categories
        icon: fa-regular fa-folder # 可以为空
      # ...... # 你可以添加更多
  # 文章日期格式
  article_date_format: auto # auto, relative, YYYY-MM-DD, YYYY-MM-DD HH:mm:ss 等
  # 文章摘要长度
  excerpt_length: 200 # 文章摘要的最大长度
  # 文章分类可见性
  categories:
    enable: true # 是否启用
    limit: 5 # 显示的最大分类数
  # 文章标签可见性
  tags:
    enable: true # 是否启用
    limit: 5 # 显示的最大标签数
# 首页文章设置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 文章 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/posts/articles
articles:
  # 设置文章样式
  style:
    font_size: 16px # 字体大小
    line_height: 1.5 # 行高
    image_border_radius: 14px # 图片边框半径
    image_alignment: center # 图片对齐方式。left, center
    image_caption: false # 是否显示图片标题
    link_icon: true # 是否显示链接图标
    delete_mask: true # 为 <del> 标签添加遮罩效果，默认隐藏内容，悬停时显示
    title_alignment: left # 标题对齐方式。left, center
    headings_top_spacing: # 标题从 h1-h6 的顶部间距
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  # 字数统计。需要 hexo-wordcount (npm install hexo-wordcount)。参见 https://github.com/willin/hexo-wordcount
  word_count:
    enable: true # 是否启用
    count: true # 是否显示字数统计
    min2read: true # 是否显示阅读时间
  # 作者标签
  author_label:
    enable: true # 是否启用
    auto: false # 是否自动添加作者标签，例如 Lv1, Lv2, Lv3...
    list: []
  # 代码块设置
  code_block:
    copy: true # 是否启用代码块复制按钮
    style: mac # mac | simple
    highlight_theme: # highlightjs 代码高亮的配色方案。预览参见 https://highlightjs.org/examples
      light: github # 亮模式主题，支持：github, atom-one-light, default
      dark: vs2015 # 暗模式主题，支持：github-dark, monokai-sublime, vs2015, night-owl, atom-one-dark, nord, tokyo-night-dark, a11y-dark, agate
    font: # 自定义字体
      enable: false # 是否启用
      family: # 字体家族
      url: # 字体 CSS 文件 URL
  # 目录设置
  toc:
    enable: true # 是否启用目录
    max_depth: 3 # 目录深度
    number: false # 是否自动为目录添加编号
    expand: true # 是否展开目录
    init_open: true # 默认打开目录
  # 是否启用版权声明
  copyright:
    enable: true # 是否启用
    default: all_rights_reserved # 默认许可，可以是 cc_by_nc_sa, cc_by_nd, cc_by_nc, cc_by_sa, cc_by, all_rights_reserved, public_domain
  # 是否启用图片懒加载
  lazyload: true
  # Pangu.js (自动在中文和英文之间添加空格)。参见 https://github.com/vinta/pangu.js
  pangu_js: true
  # 文章推荐。需要 nodejieba (npm install nodejieba)。移植自 hexo-theme-volantis。
  recommendation:
    # 是否启用文章推荐
    enable: false
    # 文章推荐标题
    title: 推荐阅读
    # 显示的最大文章数
    limit: 3
    # 移动设备上显示的最大文章数
    mobile_limit: 2
    # 占位图片
    placeholder: /images/wallhaven-wqery6-light.webp
    # 跳过目录
    skip_dirs: []
# 文章 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 评论 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/posts/comment
comment:
  # 是否启用评论
  enable: true
  # 评论系统
  system: giscus # waline, gitalk, twikoo, giscus
  # 系统配置
  config:
    # Waline 评论系统。参见 https://waline.js.org/
    waline:
      serverUrl: https://example.example.com # Waline 服务器 URL。例如 https://example.example.com
      lang: zh-CN # Waline 语言。例如 zh-CN, en-US。参见 https://waline.js.org/guide/client/i18n.html
      emoji: [] # Waline 表情，参见 https://waline.js.org/guide/features/emoji.html
      recaptchaV3Key: # Google reCAPTCHA v3 密钥。参见 https://waline.js.org/reference/client/props.html#recaptchav3key
      turnstileKey: # Turnstile 密钥。参见 https://waline.js.org/reference/client/props.html#turnstilekey
      reaction: false # Waline 反应。参见 https://waline.js.org/reference/client/props.html#reaction
    # Gitalk 评论系统。参见 https://github.com/gitalk/gitalk
    gitalk:
      clientID: # GitHub 应用程序客户端 ID
      clientSecret: # GitHub 应用程序客户端密钥
      repo: # GitHub 仓库
      owner: # GitHub 仓库所有者
      proxy: # GitHub 仓库代理
    # Twikoo 评论系统。参见 https://twikoo.js.org/
    twikoo:
      version: 1.6.10 # Twikoo 版本，如果不知道是什么，请勿修改
      server_url: # Twikoo 服务器 URL。例如 https://example.example.com
      region: # Twikoo 区域。可以为空
    # Giscus 评论系统。参见 https://giscus.app/
    giscus:
      repo: W1ndys/Blog # Github 仓库名，例如 EvanNotFound/hexo-theme-redefine
      repo_id: R_kgDOLaRaXw # Github 仓库 ID
      category: Show and tell # Github 讨论分类
      category_id: DIC_kwDOLaRaX84CeBp5 # Github 讨论分类 ID
      mapping: url # 用作页面唯一标识符的值。例如 pathname, url, title, og:title。启用 pjax 时请勿使用 og:title，因为 pjax 更改页面时不会更新 og:title
      strict: 0 # 是否启用严格模式。例如 0, 1
      reactions_enabled: 1 # 是否启用反应。例如 0, 1
      emit_metadata: 1 # 是否发出元数据。例如 0, 1
      lang: zh-CN # Giscus 语言。例如 en, zh-CN, zh-TW
      input_position: top # 将评论框放在评论上方/下方。例如 top, bottom
      loading: lazy # 懒加载评论
# 评论 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 页脚 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/footer
footer:
  # 显示网站运行时间
  runtime: true # 是否显示网站运行时间
  # 页脚图标，在此处写入 FontAwesome 图标代码
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #f54545"></i>'
  # 网站开始时间，格式：YYYY/MM/DD HH:mm:ss
  start: 2023/08/22 05:20:00
  # 网站统计
  statistics: true # 是否显示网站统计 (总文章数，总字数)
  # 页脚信息
  customize: Powered by <a href="https://github.com/W1ndys" target="_blank">W1ndys</a>
  # ICP 备案号。参见 https://beian.miit.gov.cn/
  icp:
    enable: false # 是否启用
    number: # ICP 备案号
    url: # ICP 备案 URL
# 页脚 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 注入 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/inject
inject:
  # 是否启用注入
  enable: true
  # 注入自定义头部 HTML 代码
  head:
    - <script data-pjax charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js"></script>
    - <script data-pjax>LA.init({id:"3HPYFt9znqKItrHZ",ck:"3HPYFt9znqKItrHZ",autoTrack:true})</script>
    - <link rel="stylesheet" type="text/css" href="/css/Capoo.css">

  # 注入自定义页脚 HTML 代码
  footer:
    - <script data-pjax src="/js/Capoo.js"></script>
# 注入 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 插件 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/plugins
plugins:
  # RSS 订阅。需要 hexo-generator-feed (npm i hexo-generator-feed)。参见 https://github.com/hexojs/hexo-generator-feed
  feed:
    enable: true # 是否启用
  # Aplayer。参见 https://github.com/DIYgod/APlayer
  aplayer:
    enable: false # 是否启用
    type: fixed # fixed, mini
    audios:
      - name: # 音频名称
        artist: # 音频艺术家
        url: # 音频 URL
        cover: # 音频封面 URL
        lrc: # 音频封面 LRC
  #      - name: # 音频名称
  #        artist: # 音频艺术家
  #        url: # 音频 URL
  #        cover: # 音频封面 URL
  #        lrc: # 音频封面 LRC
  # .... 你可以在此处添加更多音频
  # Mermaid JS。需要 hexo-filter-mermaid-diagrams (npm i hexo-filter-mermaid-diagrams)。参见 https://mermaid.js.org/
  mermaid:
    enable: false # 是否启用 Mermaid
    version: "11.4.1" # 默认 v11.4.1
# 插件 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 页面模板 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/page_templates
page_templates:
  # 友链页面列数
  friends_column: 3
  # 标签页面样式
  tags_style: blur # blur, cloud
# 页面模板 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# CDN >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/cdn
cdn:
  # 是否启用 CDN
  enable: true
  # CDN 提供商
  provider: aliyun # npmmirror, zstatic, cdnjs, jsdelivr, unpkg, custom
  # 自定义 CDN URL
  # 格式示例: https://cdn.custom.com/hexo-theme-redefine/${version}/source/${path}
  # ${path} 必须指向主题的 "source" 文件夹的根目录
  custom_url:
# CDN <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end

# 开发者模式 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start
# 文档: https://redefine-docs.ohevan.com/developer
developer:
  # 是否启用开发者模式 (仅供希望修改主题源代码的开发者使用，不适用于普通用户)
  enable: false
# 开发者模式 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< end
